module DevelopmentSeed
  module Config
    USER_COUNT = 20
    RANDOM_SEED = 42

    PROJECTS_PER_USER = 3

    MIN_DEVLOGS_PER_PROJECT = 1
    MAX_DEVLOGS_PER_PROJECT = 8

    MIN_COMMENTS_PER_POST = 0
    MAX_COMMENTS_PER_POST = 5

    MIN_LIKES_PER_POST = 0
    MAX_LIKES_PER_POST = 10

    MIN_REPOSTS_PER_POST = 0
    MAX_REPOSTS_PER_POST = 3

    FOLLOW_PERCENTAGE = 0.30
    PROJECT_FOLLOW_PERCENTAGE = 0.25

    STARDUST_TRANSACTIONS_PER_USER = 8
  end
end
